name: Lint Code
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Site
        uses: actions/checkout@v2
        with:
          repository: crystal-linux/getcryst.al
          path: getcryst.al

      - name: Checkout Self
        uses: actions/checkout@v3
        with:
          path: getcryst.al/_docs

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install
        working-directory: getcryst.al
        run: yarn install --frozen-lockfile

      - name: Test Build
        working-directory: getcryst.al
        run: yarn build
